### ISSUE TITLE
Weebmonkey Giveaway Link Issue

### ISSUE THREAD

**Issue by witchkrafte** [HazimAr/School-Simplified#130]
When looking at schoolsimplified.org/links on mobile, the very first tab for the giveaway seems to be a bit broken.
![2DE4A677-9CCE-4BB3-AC68-8C3E3129DA39](https://user-images.githubusercontent.com/87838541/134723890-1f9a466d-14bc-4b6b-894a-a10b5a9d165d.png)

**Comment by HazimAr** [comment]
Working on it

**Comment by daniel56483** [comment]
cleaning things up
