### ISSUE TITLE
Transcript Logging

### ISSUE THREAD

**Issue by Space-Turtle0** [HazimAr/School-Simplified#170]
**Is your feature request related to a problem? Please describe.**
In a way, yes? Basically we just need another simple website that holds and maintains transcript logs. The main problem was security and we were hoping for some Discord OAuth and logging to see who's viewing transcripts.

**Describe the solution you'd like**
Another website that holds transcripts behind Discords OAuth. Only Senior Mods should be accessing them. We also would like some logging to see who's viewed a transcript before just for weeding out leakers.

**Describe alternatives you've considered**
Modmail's LogViewer but it doesn't have Discord OAuth and anyone with the link can just view it.

**Additional context**
It's not a huge priority but we'd definitely like to get this done as quick as possible.

**Comment by HazimAr** [comment]
Something with Discord OAuth very easily can be implemented
The issue is checking roles meaning we are gonna have to run a server on the bot but your bot is in python.

**Comment by HazimAr** [comment]
The only easy fix I can see happening is me inviting a bot with perms to the server written in Discord.js and having the server in express

**Comment by sidhys1** [comment]
Can you express these nuts in your mouth?

**Comment by sidhys1** [comment]
@HazimAr @Space-Turtle0 
(https://media.discordapp.net/attachments/894329871055065149/904822224488390666/unknown.png)
