### ISSUE TITLE
Partner Page

### ISSUE THREAD

**Issue by harrychow04** [HazimAr/School-Simplified#36]
Uhh Hsu wants a Partner page, essentially exact replica of https://climatescience.org/partnerships/

We are gonna remove the map so it'll be the apply and the list of partners,sponsors, etc at the bottom

**Comment by HazimAr** [comment]
We did this

**Comment by LeftistTachyon** [comment]
According to @harrychow04, the page isn't actually created, so reopening to investigate

**Comment by LeftistTachyon** [comment]
It definitely exists: <https://schoolsimplified.org/partners>
