### ISSUE TITLE
Support Us/Donation Page

### ISSUE THREAD

**Issue by harrychow04** [HazimAr/School-Simplified#38]
Exact replica of the Contact Us page but for submitting donations and sponsorships, also will add Patreon here, ask hsu for more details regarding the Patreon. At the bottom of the page we could potentially make a list of all donators and supports

**Comment by HazimAr** [comment]
No more donate page

**Comment by IsamarZhu** [comment]
We aren't making a new one?

**Comment by LeftistTachyon** [comment]
Honestly, I have no idea

Ask upper management on this one
