### ISSUE TITLE
Recommended Accessibility Change 

### ISSUE THREAD

**Issue by Wolfhound905** [HazimAr/School-Simplified#42]
**Is your feature request related to a problem? Please describe.**
This is not a huge issue but would be better to change for accessibility issues. As the picture shows in the "Additional Context" the buttons are too small and it can be easy to mis-click another tab or the "School Simplified" logo bringing a user back the the home page.

**Describe the solution you'd like**
I believe you could convert this to a hamburger style menu.

**Describe alternatives you've considered**
Another thing may be to just make the buttons bigger some way but keeping the style. I'm not sure I would go with this.

**Additional context**
![image](https://user-images.githubusercontent.com/58155937/126559108-fa2d28d4-88c5-4560-83f7-ae296f269c94.png)

**Comment by HazimAr** [comment]
We were told to keep it like this

**Comment by LeftistTachyon** [comment]
lmao

**Comment by Wolfhound905** [comment]
bruh, this is legitimately a good idea...
