### ISSUE TITLE
Minor FAQ Response Error

### ISSUE THREAD

**Issue by witchkrafte** [HazimAr/School-Simplified#50]
Under the question "When will I be contacted about my application to School Simplified teams?" the response mentions that staff can be reached through a "#contact-staff" channel. However, the name of that channel is only "contact"

![image](https://user-images.githubusercontent.com/87838541/126939159-49ede81c-3985-4484-9b46-0f87d3c06929.png)

![image](https://user-images.githubusercontent.com/87838541/126939144-ba5d8026-a3ae-4e5d-8259-e2774133aca2.png)

**Comment by whyroland** [comment]
https://www.notion.so/FAQ-bc5b51a1b7674a1da9fd09b559844881

Fixed on Notion. Any FAQ edits are directly reflected on the website.
