### ISSUE TITLE
partner page

### ISSUE THREAD

**Issue by harrychow04** [HazimAr/School-Simplified#60]
Kinda in progress editing from bao bao, but partner page 

![image](https://user-images.githubusercontent.com/74485562/127592080-77d9f773-0515-4ffa-a071-543d75619ba5.png)

This is a very mock example, but the mirror it, below the "A Network for you to become a part of the journey" it should say "Connect with us, take advantage of our resources, and together we can build a brighter future" 

Note: this is temp wording

Then below it put the apply now button, the X on the right will be an image 

On the bottom for the partners section, there should be a button that allows you to swap between displaying what type of partners in which it will be split into 2 categories (Partners, Sponsors & Donors), 

<img width="805" alt="Screen Shot 2021-07-29 at 10 49 20 PM" src="https://user-images.githubusercontent.com/74485562/127592370-917360d4-5e49-4cf3-b408-fdc93b54a95b.png">
like this

**Comment by harrychow04** [comment]
<img width="458" alt="Screen Shot 2021-07-29 at 10 49 48 PM" src="https://user-images.githubusercontent.com/74485562/127592426-30ca59f5-8928-47be-854e-cb03ceb1eed6.png">
also rather than a link, because a lot of partners are competitors we DONT want a link to their website or itll lowkey redirect people, instead just make it display a description when you click or hover over it like shown in the ss

**Comment by LeftistTachyon** [comment]
> also rather than a link, because a lot of partners are competitors we DONT want a link to their website or itll lowkey redirect people, instead just make it display a description when you click or hover over it like shown in the ss
~~You know this repository is public right?~~ w

Current progress on this page:
![image](https://user-images.githubusercontent.com/24881514/127960413-e7c413b7-ca99-4ed7-9824-7bb5f7957640.png)
