### ISSUE TITLE
Make a https://schoolsimplified.org/links page ASAP (top priority over blog/prep since those will take a while)

### ISSUE THREAD

**Issue by Ethan-Hsu** [HazimAr/School-Simplified#62]
Make something that looks **exactly** like this https://school-simplified.tman57.repl.co/ and then push it to https://schoolsimplified.org/links make sure that ‘links’ shows up underneath the about tab on header but neglect to put it on the footer. 

Thank y’all.

**Comment by LeftistTachyon** [comment]
Done; see 3c2e7291104ea84f04fb9c5b243c5d1a4a6e240c

**Comment by yasmeene** [comment]
It's not done, I still need to finish the gradients

**Comment by LeftistTachyon** [comment]
~~oh mb~~

**Comment by LeftistTachyon** [comment]
Pasting from #69:
> <img alt="Screen Shot 2021-08-02 at 10 06 38 PM" width="447" src="https://user-images.githubusercontent.com/74485562/127946297-4f20206f-e4de-4e4d-83fa-4a761ebaf89e.png">
> 
> Remove all of the social media links at the bottom and add a "Become a Partner" option below "Contact Us"
> 
> <img alt="Screen Shot 2021-08-02 at 10 07 01 PM" width="395" src="https://user-images.githubusercontent.com/74485562/127946317-7faaccac-30ba-4e20-b115-49b4f99c449a.png">
> 
> But aside from this is there anyway to make this linked to like notion or something so we can regularly update links because there are a lot more links than this and there is also a lot of application links that are for specific positions and only last like a week

**Comment by LeftistTachyon** [comment]
Btw @harrychow04 I think it'd be more prudent to have this stay the same and have advertisements to our positions elsewhere since it makes no sense to have those things plastered everywhere. It only makes us look desperate and scatterbrained
